server:
  port: 9003

spring:
  application:
    name: khyou-board-article-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/article_view
    username: root
    password: dbrlgns123@
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379