server:
  port: 9001
spring:
  application:
    name: khyou-board-comment-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/comment
    username: root
    password: dbrlgns123@
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

